import 'reflect-metadata';
import { container } from 'tsyringe';
import { PrismaClient } from '@prisma/client';
import { logger } from './logger.js';
import { createPrismaClient } from '../infrastructure/database/prisma.client.js';
import { PrismaBudgetRepository } from '../infrastructure/database/repositories/PrismaBudgetRepository.js';
import { PrismaBudgetMemberRepository } from '../infrastructure/database/repositories/PrismaBudgetMemberRepository.js';
import { PrismaBudgetInviteRepository } from '../infrastructure/database/repositories/PrismaBudgetInviteRepository.js';
import { PrismaPersonRepository } from '../infrastructure/database/repositories/PrismaPersonRepository.js';
import { PrismaCategoryRepository } from '../infrastructure/database/repositories/PrismaCategoryRepository.js';
import { PrismaExpenseRepository } from '../infrastructure/database/repositories/PrismaExpenseRepository.js';
import { PrismaLoanDetailRepository } from '../infrastructure/database/repositories/PrismaLoanDetailRepository.js';
import { PrismaLoanPaymentRepository } from '../infrastructure/database/repositories/PrismaLoanPaymentRepository.js';
import { PrismaRevenueRepository } from '../infrastructure/database/repositories/PrismaRevenueRepository.js';
import { PrismaSavingRepository } from '../infrastructure/database/repositories/PrismaSavingRepository.js';

const prisma = createPrismaClient();
container.registerInstance(PrismaClient, prisma);
container.registerInstance('Logger', logger);
container.register('IBudgetRepository', { useClass: PrismaBudgetRepository });
container.register('IBudgetMemberRepository', { useClass: PrismaBudgetMemberRepository });
container.register('IBudgetInviteRepository', { useClass: PrismaBudgetInviteRepository });
container.register('IPersonRepository', { useClass: PrismaPersonRepository });
container.register('ICategoryRepository', { useClass: PrismaCategoryRepository });
container.register('IExpenseRepository', { useClass: PrismaExpenseRepository });
container.register('ILoanDetailRepository', { useClass: PrismaLoanDetailRepository });
container.register('ILoanPaymentRepository', { useClass: PrismaLoanPaymentRepository });
container.register('IRevenueRepository', { useClass: PrismaRevenueRepository });
container.register('ISavingRepository', { useClass: PrismaSavingRepository });

export { container, prisma };
